[project]
name = "neo4j-cms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "cms",
    "neo4j>=5.28.1",
    "setuptools>=76.0.0",
]

[tool.uv.sources]
cms = { path = "cms", editable = true }
